---
deployment:
  tasks:
    - export REPO=SVGMotionBrush
    # Make a folder for the Repository in the user's home directory. 
    - mkdir -p ~/$REPO
    # Copy files to the Repository folder
    - cp -R * ~/$REPO
    # remove any existing references to the Repository in Apache's public_html folder
    - rm -rf ~/public_html/$REPO
    # Make a symbolic link from Apache's public_html folder to the Repository's public folder.
    - ln -s ~/$REPO/public ~/public_html/$REPO