# This is a workflow to publish to CPanel via SSH and RSync
# We use @shimataro's ssh-key-action https://github.com/marketplace/actions/install-ssh-key

# You must setup the following secrets (GitHub > Settings > Secrets)

# SSH_PRIVATE_KEY
# You can create this key in CPanel. (Dashboard > SSH Access > Manage Keys) 
# Copy the contents of the Private Key file to SSH_PRIVATE_KEY 
# Be sure to authorize the Key in CPanel after creating it. 

# SSH_USER
# This is your CPanel username

# SSH_HOST
# This is your CPanel server hostname

name: Publish Website to CPanel via SSH and RSync

# Ths workflow runs whenever we push to the main branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # This lets you run this workflow manually from the Actions tab

jobs:
  Deploy-To-CPanel:
    name: Deploy to CPanel via SSH and rsync
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: "default" 
        
     # we will add our server dynamically below
    - name: Add CPanel Server to Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
    - name: rsync over SSH
      run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/public_html/SVGMotionBrush/
      
